const projects = [
  {
    id: 1,
    date: '2023',
    name: 'Aldea Explorer',
    description:
      'Design of a web app for exploring the Aldea blockchain. It allows users to view the blockchain, search for transactions, blocks, packages, and more.',
    image: './images/dragon-repeller.png',
    role: 'Head of Design',
    tools: ['Figma', 'Adobe Suite', 'Tailwind'],
    tags: ['UX/UI', 'Web Design', 'Web Development'],
    client: 'Aldea',
    isComingSoon: false,
  },
  {
    id: 2,
    date: '2021',
    name: 'Revamp Toysa website',
    description: 'Redesign and ux improvement of a store website.',
    image: './images/dragon-repeller.png',
    role: 'UX Designer',
    tools: ['Figma'],
    tags: ['UX/UI', 'Web Design'],
    client: 'Toysa',
    isComingSoon: false,
  },
  {
    id: 3,
    date: '2021',
    name: 'Ruky',
    description: 'Redesign and ux improvement of a store website.',
    image: './images/dragon-repeller.png',
    role: 'UX Designer',
    tools: ['Figma', 'Adobe Suite'],
    tags: ['Product Design', 'UX/UI', 'Web Design'],
    client: 'Forge Foundation',
    isComingSoon: false,
  },
  {
    id: 4,
    date: '2022',
    name: 'Aldea Brand',
    description: 'Redesign and ux improvement of a brand website.',
    image: './images/dragon-repeller.png',
    role: 'UX Designer',
    tools: ['Figma', 'Adobe Suite'],
    tags: ['Product Design', 'UX/UI', 'Web Design'],
    client: 'Aldea',
    isComingSoon: false,
  },
  {
    id: 5,
    date: 'January 2025',
    name: 'SoundScape',
    description: 'A collaborative music production and sharing platform.',
    image: './images/dragon-repeller.png',
    role: 'UI Designer',
    tools: ['Figma', 'Web Audio API', 'Node.js'],
    tags: ['Music', 'Collaboration', 'Real-time'],
    client: 'AudioWave',
    isComingSoon: false,
  },
  {
    id: 6,
    date: 'December 2024',
    name: 'ARchitect',
    description:
      'Augmented reality app for interior design and furniture placement. It allows users to design their interiors and see the impact of their choices.',
    image: './images/dragon-repeller.png',
    role: 'AR/VR Designer',
    tools: ['Unity', 'Blender', 'ARKit'],
    tags: ['AR', 'Interior Design', '3D'],
    client: 'SpaceCraft',
    isComingSoon: false,
  },
  {
    id: 7,
    date: 'December 2024',
    name: 'Mini Games',
    description: 'A collection of mini games for the Aldea blockchain.',
    image: './images/dragon-repeller.png',
    role: 'UX Designer',
    tools: ['Figma', 'Adobe Suite'],
    tags: '',
    client: null,
    isComingSoon: true,
  },
];

export default projects;
