const projects = [
  {
    id: 1,
    date: '2022',
    name: 'Aldea Explorer',
    description: 'Design of a web app for exploring the Aldea blockchain.',
    image: '/images/projects/aldea-explorer.png',
    role: 'Product & UX/UI Designer',
    tools: ['Figma', 'Adobe Suite', 'Tailwind'],
    tags: ['UX/UI', 'Design System', 'Blockchain'],
    client: 'Aldea',
    isComingSoon: false,
    link: 'https://explorer.aldea.io/',
    projectContent: 'aldea-explorer.md',
  },
  {
    id: 2,
    date: '2021',
    name: 'Revamp Toysa E-commerce',
    description: 'Redesign and ux improvement of a store website.',
    image: '/images/projects/toysa.png',
    role: 'UX/UI Designer',
    tools: ['Figma'],
    tags: ['UX/UI', 'Web Design', 'Redesign'],
    client: 'Toysa',
    isComingSoon: false,
    link: 'https://toysa.com/',
    projectContent: 'toysa.md',
  },
  {
    id: 3,
    date: '2021',
    name: 'Pirca Website',
    description: 'Brand Identity & Website Development.',
    image: '/images/projects/pirca.png',
    role: 'Designer & Frontend Developer',
    tools: ['Figma', 'HTML', 'CSS', 'JavaScript'],
    tags: ['UX/UI', 'Illustration', 'Frontend Development'],
    client: 'Pirca',
    isComingSoon: false,
    link: 'https://pircasolutions.com/',
    projectContent: 'pirca.md',
  },
  {
    id: 4,
    date: '2021',
    name: 'Ruky',
    description: 'Product & UX/UI Design',
    image: '/images/projects/ruky_cover.png',
    role: 'Product & UX/UI Designer (end-to-end)',
    tools: ['Figma'],
    tags: ['UX/UI', 'Product Design', 'Design System', 'Gamification'],
    client: 'Forge Foundation',
    isComingSoon: false,
    link: 'https://www.figma.com/proto/48H6Mj4GdZPoMPR0RAUtVj/Ruky?page-id=713%3A231&node-id=713-232&p=f&viewport=315%2C-40%2C0.05&t=UY7Wy6E4fL0knNNs-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=713%3A232&show-proto-sidebar=1',
    projectContent: 'ruky.md',
  },
  {
    id: 4,
    date: '2022',
    name: 'Digital Wallet',
    description: 'Design of a digital wallet in-app for Buzzcast',
    image: '/images/projects/coming-soon.png',
    role: 'Product & UX/UI Designer',
    tools: ['Figma'],
    tags: ['UX/UI', 'Product Design', 'Design System'],
    client: 'Buzzcast',
    isComingSoon: true,
    link: '',
    projectContent: '',
  },
  {
    id: 5,
    date: '2021-2024',
    name: 'Mini Games',
    description: 'Design of a mini games',
    image: '/images/projects/coming-soon.png',
    role: 'Frontend Developer',
    tools: ['Figma'],
    tags: ['UX/UI', 'Frontend Development', 'Game Design'],
    client: '',
    isComingSoon: true,
    link: '',
    projectContent: '',
  },
  {
    id: 5,
    date: '2021',
    name: 'Tuba',
    description:
      'Tuba is a data analysis and visualization platform for decision-making in companies.',
    image: '/images/projects/coming-soon.png',
    role: 'UX/UI Designer',
    tools: ['Figma'],
    tags: ['UX/UI', 'Web Design', 'Data Visualization', 'Human resources'],
    client: 'Tuba',
    isComingSoon: true,
    link: '',
    projectContent: '',
  },
];

export default projects;
